apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
 containers:
 - image: wordpress:latest
   name: wp
   ports:
   - containerPort: 80
   env:
   - name: WORDPRESS_DB_HOST
     value: wordpress
   - name: WORDPRESS_DB_USER
     value: root
   - name: WORDPRESS_DB_PASSWORD
     value: test123
   - name: WORDPRESS_DB_NAME
     value: wordpress
   - name: WORDPRESS_TABLE_PREFIX
     value: wp_
 - name: db
   image: mysql:latest
   ports:
   - containerPort: 3306
   env:
   - name: MYSQL_ROOT_PASSWORD
     value: test123
   - name: MYSQL_DATABASE
     value: wordpress
