apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
 containers:
 - name: wp
   image: wordpress:latest
   ports:
   - containerPort: 80
   envFrom:
   - configMapRef:
       name: mywpenv
