apiVersion: v1
kind: Pod
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
 containers:
 - name: wp
   image: wordpress:latest
   ports:
   - containerPort: 80
   env:
   - name: WORDPRESS_DB_HOST
     valueFrom:
       configMapKeyRef:
          name: mywpenv
          key: WORDPRESS_DB_HOST
   - name: WORDPRESS_DB_USER
     value: root
   - name: WORDPRESS_DB_PASSWORD
     value: test123
   - name: WORDPRESS_DB_NAME
     value: wordpress
   - name: WORDPRESS_TABLE_PREFIX
     value: wp_
 
