apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: mypod2
spec:
  containers:
  - name: con1
    image: nginx:latest
    ports:
    - containerPort: 80
  nodeSelector:
    cpu: intel
