apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: podaff2
spec:
  containers:
  - name: con1
    image: nginx:latest
    ports:
    - containerPort: 80
  affinity:
   podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - mango
          topologyKey: kubernetes.io/hostname
