apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: podaff1
spec:
  containers:
  - name: con1
    image: nginx:latest
    ports:
    - containerPort: 80
  affinity:
    podAntiAffinity:   # set affinity or anti-affinity here ...
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - mango
        topologyKey: kubernetes.io/hostname
