apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mango
  name: tolpod
spec:
  containers:
  - name: con1
    image: nginx:latest
    ports:
    - containerPort: 80
  tolerations:
  - key: "color"
    operator: "Equal"
    value: "red"
    effect: "NoExecute"
 
